name: Protein_SS3_Task_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.11
  - pip=20.2.4
  - pytorch=1.7
  - numpy=1.19.2
  - requests=2.25.0
  - clint=0.5.1
  - pip:
    - pytorch_lightning==1.0.8
    - test_tube==0.7.5
    - configargparse==1.2.3

